regions:
- sa-east-1 # Sao Paulo
- us-east-1 # North Virginia
- eu-central-2 # Zürich
- eu-central-1 # Frankfurt
- eu-north-1 # Stockholm
- eu-west-1 # Ireland
- global

account-blocklist:
- "999999999999" # production

resource-types:
  excludes:
  - Budget
  - IAMVirtualMFADevice

accounts:
  "296119450228":
    filters:
      IAMUser:
      - "axiom"
      - "nuker"
      - type: "glob"
        value: "*tfc*"
      IAMVirtualMFADevice:
      - type: "glob"
        value: "*"
      IAMUserPolicyAttachment:
      - "axiom -> AdministratorAccess"
      - "nuker -> AdministratorAccess"
      - type: "glob"
        value: "*tfc* -> AdministratorAccess"
      IAMUserAccessKey:
      - type: "glob"
        value: "axiom -> *"
      - type: "glob"
        value: "nuker -> *"
      - type: "glob"
        value: "*tfc* -> *"
