# https://ekristen.github.io/aws-nuke/starter-config/
blocklist:
  - "999999999999" # production

regions:
  - sa-east-1 # Sao Paulo
  - us-east-1 # North Virginia
  - eu-central-2 # Zürich
  - eu-central-1 # Frankfurt
  - eu-north-1 # Stockholm
  - eu-west-1 # Ireland
  - global

settings:
  EC2Image:
    IncludeDisabled: true
    IncludeDeprecated: true
    DisableDeregistrationProtection: true
  EC2Instance:
    DisableStopProtection: true
    DisableDeletionProtection: true
  RDSInstance:
    DisableDeletionProtection: true
  CloudFormationStack:
    DisableDeletionProtection: true
  DynamoDBTable:
    DisableDeletionProtection: true

resource-types:
  excludes:
    - IAMRolePolicyAttachment # can still delete the roles and policies
    - S3Object # Excluded because S3 bucket removal handles removing all S3Objects
    - ServiceCatalogTagOption # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - ServiceCatalogTagOptionPortfolioAttachment # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - FMSNotificationChannel # Excluded because it's not available
    - FMSPolicy # Excluded because it's not available
    - MachineLearningMLModel # Excluded due to ML being unavailable
    - MachineLearningDataSource # Excluded due to ML being unavailable
    - MachineLearningBranchPrediction # Excluded due to ML being unavailable
    - MachineLearningEvaluation # Excluded due to ML being unavailable
    - RoboMakerDeploymentJob # Deprecated Service
    - RoboMakerFleet # Deprecated Service
    - RoboMakerRobot # Deprecated Service
    - RoboMakerSimulationJob
    - RoboMakerRobotApplication
    - RoboMakerSimulationApplication
    - OpsWorksApp # Deprecated service
    - OpsWorksInstance # Deprecated service
    - OpsWorksLayer # Deprecated service
    - OpsWorksUserProfile # Deprecated service
    - OpsWorksCMBackup # Deprecated service
    - OpsWorksCMServer # Deprecated service
    - OpsWorksCMServerState # Deprecated service
    - CodeStarProject # Deprecated service
    - CodeStarConnection # Deprecated service
    - CodeStarNotification # Deprecated service
    - Cloud9Environment # Deprecated service
    - CloudSearchDomain # Deprecated service
    - RedshiftServerlessSnapshot # Deprecated service
    - RedshiftServerlessNamespace # Deprecated service
    - RedshiftServerlessWorkgroup # Deprecated service

presets:
  common:
    filters:
      BudgetsBudget:
        - property: Name
          value: "default"
  defaults:
    filters:
      EC2Subnet:
        - property: DefaultVPC
          value: "true"
      EC2DefaultSecurityGroupRule:
        - property: DefaultVPC
          value: "true"
      EC2DHCPOption:
        - property: DefaultVPC
          value: "true"
      EC2VPC:
        - property: IsDefault
          value: "true"
      EC2InternetGateway:
        - property: DefaultVPC
          value: "true"
      EC2InternetGatewayAttachment:
        - property: DefaultVPC
          value: "true"
  terraform:
    filters:
      __global__:
        - property: tag:managed-by
          value: "terraform"

# this list represents only static things needed for the account to work and terraform resources managed somewhere else
# they are all created manually
accounts:
  "351425708426": # technat account
    presets:
      - "terraform"
      - "defaults"
      - "common"
    filters:
      IAMUser:
        - "technat"
      IAMVirtualMFADevice:
        - "arn:aws:iam::351425708426:mfa/bitwarden"
      IAMUserMFADevice:
        - "technat -> passkey_apple-FUUYS55HZRFOXMNAEIRDA3NBSU"
      IAMLoginProfile:
        - "technat"
      IAMUserPolicyAttachment:
        - "technat -> AdministratorAccess"
      IAMRole:
        - "nuker"
      IAMRolePolicyAttachement:
      - "nuker -> AdministratorAccess"
      IAMOpenIDConnectProvider:
        - "arn:aws:iam::351425708426:oidc-provider/token.actions.githubusercontent.com"
