regions:
- sa-east-1 # Sao Paulo
- us-east-1 # North Virginia
- eu-central-2 # Zürich
- eu-central-1 # Frankfurt
- eu-north-1 # Stockholm
- eu-west-1 # Ireland
- global

account-blocklist:
- "999999999999" # production

resource-types:
  excludes:
  # don't nuke OpenSearch Packages, see https://github.com/rebuy-de/aws-nuke/issues/1123
  - OSPackage
  - IAMRolePolicyAttachment # can still delete the roles
  - S3Bucket

accounts:
  "351425708426": # technat account
    filters:
      Budget:
      - "default"
      S3Bucket:
      - "s3://grapesstate"
      - "grapesstate"
      IAMUser:
      - "technat"
      IAMVirtualMFADevice:
      - type: glob
        value: "arn:aws:iam::351425708426:mfa/*"
      IAMLoginProfile:
      - type: glob
        value: "*technat*"
      IAMUserAccessKey:
      - type: "glob"
        value: "technat -> *"
      IAMUserPolicyAttachment:
      - "technat -> AdministratorAccess"
      IAMRole:
      - "nuker"
      - type: glob
        value: "tfc-*"
      - type: glob
        value: "gh-*"
      IAMPolicy:
      - type: glob
        value: "gh-*"
      - type: glob
        value: "tfc-*"
      IAMOpenIDConnectProvider:
      - "arn:aws:iam::351425708426:oidc-provider/token.actions.githubusercontent.com"
      - "arn:aws:iam::351425708426:oidc-provider/app.terraform.io"
      
