regions:
- sa-east-1 # Sao Paulo
- us-east-1 # North Virginia
- eu-central-2 # Zürich
- eu-central-1 # Frankfurt
- eu-north-1 # Stockholm
- eu-west-1 # Ireland

account-blocklist:
- "999999999999" # production

resource-types:
  excludes:
  - Budget
  - IAMVirtualMFADevice
  # don't nuke OpenSearch Packages, see https://github.com/rebuy-de/aws-nuke/issues/1123
  - OSPackage
  - S3Bucket

accounts:
  "296119450228": # grapes account
    filters:
      S3Bucket:
      - type: "glob"
        value: "*grapes*"
