regions:
- sa-east-1 # Sao Paulo
- us-east-1 # North Virginia
- eu-central-2 # Zürich
- eu-central-1 # Frankfurt
- eu-north-1 # Stockholm
- eu-west-1 # Ireland
- global

account-blocklist:
- "999999999999" # production

resource-types:
  excludes:
  - Budget
  - IAMVirtualMFADevice
  # don't nuke OpenSearch Packages, see https://github.com/rebuy-de/aws-nuke/issues/1123
  - OSPackage

accounts:
  "296119450228": # grapes account
    filters:
      S3Bucket:
      - type: "glob"
        value: "*grapes*"
      IAMUser:
      - "grapes"
      - "nuker" # not used
      IAMUserPolicyAttachment:
      - "grapes -> AdministratorAccess"
      - "nuker -> AdministratorAccess" # not used
      IAMUserAccessKey:
      - type: "glob"
        value: "grapes -> *"
      - type: "glob"
        value: "nuker -> *" # not used
