regions:
- sa-east-1 # Sao Paulo
- us-east-1 # North Virginia
- eu-central-2 # Zürich
- eu-central-1 # Frankfurt
- eu-north-1 # Stockholm
- eu-west-1 # Ireland
- global

account-blocklist:
- "999999999999" # production

resource-types:
  excludes:
  # don't nuke OpenSearch Packages, see https://github.com/rebuy-de/aws-nuke/issues/1123
  - OSPackage

accounts:
  "351425708426": # technat-grapes account
    filters:
      Budget:
      - "default"
      S3Bucket:
      - "grapesstate"
      IAMUser:
      - "technat"
      IAMVirtualMFADevice:
			- type: glob
				value: "arn:aws:iam::351425708426:mfa/*"
			IAMLoginProfile:
			- type: glob
				value: "*technat*"
      IAMUserPolicyAttachment:
      - "technat -> AdministratorAccess"
      IAMRole:
      - "nuker"
      - type: glob
        value: "tfc-*"
      - type: glob
        value: "gh-*"
      IAMRolePolicyAttachment:
      - "gh-* -> *"
      - "tfc-* -> *"
      - "nuker -> AdministratorAccess"
      IAMOpenIDConnectProvider:
      - "app.terraform.io"
      - "token.actions.githubusercontent.com"
      
