regions:
  - sa-east-1 # Sao Paulo
  - us-east-1 # North Virginia
  - eu-central-2 # Zürich
  - eu-central-1 # Frankfurt
  - eu-north-1 # Stockholm
  - eu-west-1 # Ireland
  - global

blocklist:
  - "999999999999" # production

resource-types:
  excludes:
    # don't nuke OpenSearch Packages, see https://github.com/rebuy-de/aws-nuke/issues/1123
    - OSPackage
    - IAMRolePolicyAttachment # can still delete the roles and policies

presets:
  core:
    filters:
      __global__:
        - property: tag:managed-by
          value: "terraform"

# this list represents only static things needed for the account to work (and the core repo to work)
accounts:
  "351425708426": # technat account
    presets:
      - "core"
    filters:
      IAMUser:
        - "technat"
      IAMVirtualMFADevice:
        - "arn:aws:iam::351425708426:mfa/bitwarden"
      IAMUserMFADevice:
        - "technat -> passkey_apple-FUUYS55HZRFOXMNAEIRDA3NBSU"
      IAMLoginProfile:
        - "technat"
      IAMUserPolicyAttachment:
        - "technat -> AdministratorAccess"
      IAMOpenIDConnectProvider:
        - "arn:aws:iam::351425708426:oidc-provider/app.terraform.io"
