# https://ekristen.github.io/azure-nuke/quick-start/
blocklist:
  - 00001111-2222-3333-4444-555566667777 # production

regions:
  - switzerlandnorth # Zürich
  - europe
  - germany
  - switzerland
  - germanynorth
  - switzerlandwest # Geneva
  - global
  - eastus
  - eastus2

presets:
  terraform:
    filters:
      __global__:
        - property: tag:managed-by
          value: "terraform"


# this list represents only static things needed for the account to work (and the core repo to work)
# they are all created manually
accounts:
  afb1b04e-8a6f-44e6-8835-db3a1ab8bee7: # technat sub
    presets:
    - "terraform" # to filter everything that terraform created and manages
    filters:
      AzureADUser:
      - "Nathanael Liechti"
      Application:
      - "nuker" 
      ApplicationSecret:
      - "nuker -> b9603806-d7a2-4119-adc5-a9f3225ab081"
      ServicePrincipal:
      - "nuker"
      SubscriptionRoleAssignment:
      - "nuker -> Contributor" 
