tenant-blocklist:
  - 00001111-2222-3333-4444-555566667777

tenants:
  afb1b04e-8a6f-44e6-8835-db3a1ab8bee7:
    filters:
      ServicePrincipal:
        - type: contains
          property: Name
          value: nuker
          
presets:
  common:
    filters:
      ResourceGroup:
        - containerday
