name: aws-nuke

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 23 * * sun,wed'

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    env:
      aws_nuke_version: "v2.25.0"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch secrets from AKeyless
        id: fetch-secrets
        uses: LanceMcCarthy/akeyless-action@v3
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          static-secrets: '{"/actions/grapes/aws_access_key":"AWS_ACCESS_KEY_ID", "/actions/grapes/aws_secret_access_key": "AWS_SECRET_ACCESS_KEY"}'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-2
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      - name: Install aws-nuke
        run: |
          curl -Lo aws-nuke.tar.gz https://github.com/rebuy-de/aws-nuke/releases/download/${{ env.aws_nuke_version }}/aws-nuke-${{ env.aws_nuke_version }}-linux-amd64.tar.gz
          tar -zxvf aws-nuke.tar.gz
          sudo mv aws-nuke-${{ env.aws_nuke_version }}-linux-amd64 /usr/local/bin/aws-nuke
          rm aws-nuke.tar.gz
      - name: Run aws-nuke
        run: aws-nuke --no-dry-run --force -c aws-nuke-config.yml
