name: Hcloud Go Checks 

on:
  pull_request:

jobs:

  audit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build
      run: go build -v hcloud-nuker/...

    - name: Run go vet
      run: go vet hcloud-nuker/...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck hcloud-nuker/...

    - name: Run tests
      run: go test -race -vet=off hcloud-nuker/...
